// ============================================================
//  build-env.js — Injects environment variables at build time
//  Run by Netlify during build: `node build-env.js`
// ============================================================

const fs = require('fs');
const path = require('path');

const geminiKey = process.env.GEMINI_API_KEY || '';
const groqKey = process.env.GROQ_API_KEY || '';
const openrouterKey = process.env.OPENROUTER_API_KEY || '';
const cohereKey = process.env.COHERE_API_KEY || '';
const unsplashKey = process.env.UNSPLASH_ACCESS_KEY || '';
const tmdbKey = process.env.TMDB_API_KEY || '';

// SECURITY: this file is published to the web root, so anything written here is
// readable by every visitor. Deliberately emit EMPTY values — the real keys stay in
// Netlify's environment and are only ever read server-side by the proxy functions.
// (Local development still uses a hand-written js/env.js, which is gitignored.)
const content = `// Auto-generated by build-env.js at build time — DO NOT EDIT
// Intentionally empty: production talks to the serverless proxies, which read the
// real keys from the server environment. Never put live keys in this file.
export const ENV_KEYS = {
  geminiKey:   "",
  groqKey:     "",
  openrouterKey: "",
  cohereKey:   "",
  unsplashKey: "",
  tmdbKey:     ""
};
`;

const dir = path.join(__dirname, 'js');
if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
}

fs.writeFileSync(path.join(dir, 'env.js'), content, 'utf8');

console.log('✅ js/env.js generated (empty by design — keys stay server-side)');
// Report presence only, never the value, so build logs stay safe to share.
const present = name => (process.env[name] ? '   • ' + name + ' available to functions' : '   ○ ' + name + ' not set');
['GEMINI_API_KEY','GROQ_API_KEY','OPENROUTER_API_KEY','COHERE_API_KEY','TMDB_API_KEY','UNSPLASH_ACCESS_KEY',
 'TURSO_DATABASE_URL','TURSO_AUTH_TOKEN','ADMIN_PASSCODE'].forEach(n => console.log(present(n)));
if (!geminiKey && !groqKey && !openrouterKey && !cohereKey) {
    console.log('   ⚠️  No AI keys found — AI features will not work');
}
