// ============================================================
//  build-env.js — Injects environment variables at build time
//  Run by Netlify during build: `node build-env.js`
// ============================================================

const fs = require('fs');
const path = require('path');

const geminiKey = process.env.GEMINI_API_KEY || '';
const groqKey = process.env.GROQ_API_KEY || '';
const openrouterKey = process.env.OPENROUTER_API_KEY || '';
const cohereKey = process.env.COHERE_API_KEY || '';
const unsplashKey = process.env.UNSPLASH_ACCESS_KEY || '';

const content = `// Auto-generated by build-env.js at build time — DO NOT EDIT
// This file is overwritten by Netlify on every deploy.
export const ENV_KEYS = {
  geminiKey:   "${geminiKey}",
  groqKey:     "${groqKey}",
  openrouterKey: "${openrouterKey}",
  cohereKey:   "${cohereKey}",
  unsplashKey: "${unsplashKey}"
};
`;

const dir = path.join(__dirname, 'js');
if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
}

fs.writeFileSync(path.join(dir, 'env.js'), content, 'utf8');

console.log('✅ js/env.js generated');
if (geminiKey) console.log('   • GEMINI_API_KEY set');
if (groqKey) console.log('   • GROQ_API_KEY set');
if (openrouterKey) console.log('   • OPENROUTER_API_KEY set');
if (cohereKey) console.log('   • COHERE_API_KEY set');
if (unsplashKey) console.log('   • UNSPLASH_ACCESS_KEY set');
if (!geminiKey && !groqKey && !openrouterKey && !cohereKey) console.log('   ⚠️  No AI keys found — AI features will not work');
